cc_test(
    name = "hello_lib_test",
    srcs = ["hello_lib_test.cc"],
    deps = [
        "//lib:hello_lib",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "calculator_test",
    srcs = ["calculator_test.cc"],
    deps = [
        "//lib:calculator",
        "@com_google_googletest//:gtest_main",
    ],
)